"""Report generator for vulnerability scan results."""

from __future__ import annotations

import json
import os
from dataclasses import asdict
from datetime import datetime

from jinja2 import Template

from vulnscan.models import ScanResult, VulnType

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>VulnScan Report - {{ result.target }}</title>
<style>
  body { font-family: -apple-system, sans-serif; margin: 40px; background: #f5f5f5; color: #333; }
  h1 { color: #c0392b; border-bottom: 2px solid #c0392b; padding-bottom: 8px; }
  .summary { background: #fff; padding: 20px; border-radius: 8px; margin: 20px 0; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
  .summary span { font-weight: bold; }
  .stat { display: inline-block; margin-right: 30px; }
  .vuln-card { background: #fff; padding: 16px 20px; border-radius: 8px; margin: 12px 0;
               border-left: 4px solid #e74c3c; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
  .vuln-card.high { border-left-color: #e74c3c; }
  .vuln-card.medium { border-left-color: #f39c12; }
  .vuln-card.low { border-left-color: #3498db; }
  .vuln-card.info { border-left-color: #95a5a6; }
  .vuln-type { font-weight: bold; color: #c0392b; text-transform: uppercase; font-size: 0.85em; }
  .vuln-url { color: #2980b9; word-break: break-all; }
  .detail { font-family: monospace; background: #f8f8f8; padding: 8px; border-radius: 4px;
            margin: 8px 0; font-size: 0.9em; white-space: pre-wrap; word-break: break-all; }
  .footer { margin-top: 30px; color: #999; font-size: 0.85em; }
</style>
</head>
<body>
<h1>VulnScan Report</h1>

<div class="summary">
  <div class="stat">Target: <span>{{ result.target }}</span></div>
  <div class="stat">Pages: <span>{{ result.pages_crawled }}</span></div>
  <div class="stat">Forms: <span>{{ result.forms_found }}</span></div>
  <div class="stat">Vulnerabilities: <span style="color:#e74c3c">{{ result.vulnerabilities|length }}</span></div>
  <div class="stat">Scan time: <span>{{ timestamp }}</span></div>
</div>

{% for vuln in result.vulnerabilities %}
<div class="vuln-card {{ vuln.severity.value }}">
  <div class="vuln-type">{{ vuln.vuln_type.value }} &mdash; {{ vuln.severity.value | upper }}</div>
  <div class="vuln-url">{{ vuln.url }}</div>
  <p><strong>Parameter:</strong> {{ vuln.parameter }} &nbsp;|&nbsp; <strong>Payload:</strong> {{ vuln.payload }}</p>
  <div class="detail">{{ vuln.evidence }}</div>
</div>
{% endfor %}

{% if not result.vulnerabilities %}
<div class="summary" style="text-align:center; color: #27ae60;">
  <h2>No vulnerabilities found.</h2>
</div>
{% endif %}

<div class="footer">
  Generated by VulnScan {{ version }} &mdash; {{ timestamp }}
</div>
</body>
</html>
"""


def generate_json(result: ScanResult, output_dir: str) -> str:
    """Generate a JSON report. Returns the output file path."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "scan_results.json")

    data = asdict(result)
    data["scan_time"] = datetime.now().isoformat()

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)

    return path


def generate_html(result: ScanResult, output_dir: str, version: str = "0.1.0") -> str:
    """Generate an HTML report. Returns the output file path."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "scan_report.html")

    template = Template(HTML_TEMPLATE)
    html = template.render(
        result=result,
        version=version,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

    return path
